package com.MelloTech.ReceipeSharing;

import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;

// MongoDB collection name for this entity
@Document(value = "RecipePost")
public class Post {


    public Post() {
    }

    private String id; // Unique identifier automatically generated by mongodb
    private String name; // Name of the recipe
    private String description; // Description of the recipe
    private List<String> ingredients; // List of ingredients required for the recipe
    private List<String> directions; // List of directions to make the recipe
    private String image; // URL link the image of the recipe
    private String authorId; // ID of the author who created the recipe
    private List<String> tags; // List of tags for recipe

    // Getters and setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<String> getIngredients() {
        return ingredients;
    }

    public void setIngredients(List<String> ingredients) {
        this.ingredients = ingredients;
    }

    public List<String> getDirections() {
        return directions;
    }

    public void setDirections(List<String> directions) {
        this.directions = directions;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getAuthorId() {
        return authorId;
    }

    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    // Overriding the toString() method
    @Override
    public String toString() {
        return "Post{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", ingredients=" + ingredients +
                ", directions=" + directions +
                ", image='" + image + '\'' +
                ", authorId='" + authorId + '\'' +
                ", tags=" + tags +
                '}';
    }
}
